
services:
  postgres:
    image: postgres:16-alpine
    container_name: dnd_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: dnd_user
      POSTGRES_PASSWORD: dnd_secret
      POSTGRES_DB: dnd_campaign_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
